name: Github Actions on Main branch
on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
jobs:
  Github-Actions-Main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ Automatic trigger for push in Main branch"
